gihub, ci: add tests for lab locking mechanism
add missing tests for the lab locking mechanism.

Signed-off-by: Heiko Schocher <hs@denx.de>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -101,4 +101,12 @@ jobs:
             echo "doing all sisyphus build host tests failed"
             returncode=1
           fi
+          # now check board locking
+          cp ../scripts/ci/check_lab_locking.sh .
+          ./check_lab_locking.sh
+          exitcode="$?"
+          if [[ "${exitcode}" != "0" ]];then
+            echo "checking lab locking mechanism failed"
+            returncode=1
+          fi
           exit "${returncode}"
