ci.yml: check tbot error codes
check return code from tbot calls and fail in case of errors.

Signed-off-by: Heiko Schocher <hs@denx.de>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -66,23 +66,39 @@ jobs:
           # correct path to keyfile
           sed -i "s|/home/\${username}/.ssh/id_rsa|~/.ssh/staging.key|g" tbotconfig/foo/tbot.ini
           echo "----- Test commandline completion ------------------------------------"
+          set +e
+          returncode=0
           RET=$(tbottest/newtbot_starter.py @tbotconfig/foo/args/argsfoo-noeth --complete-module tbotco)
           if [[ "${RET}" != "tbotconfig" ]];then
             echo "Commandline completion module failed"
-            exit 1
+            returncode=1
           fi
           RET=$(tbottest/newtbot_starter.py @tbotconfig/foo/args/argsfoo-noeth --complete-module tbotconfig.in)
           if [[ "${RET}" != "tbotconfig.interactive" ]];then
             echo "Commandline completion module second level failed"
-            exit 1
+            returncode=1
           fi
           RET=$(tbottest/newtbot_starter.py @tbotconfig/foo/args/argsfoo-noeth --complete-testcase tbotconfig.interactive.la)
           if [[ "${RET}" != "tbotconfig.interactive.lab" ]];then
             echo "Commandline completion testcase failed"
-            exit 1
+            returncode=1
           fi
           echo "----- now try to login into lab with tbot setup and do all tests -----"
           tbottest/newtbot_starter.py @tbotconfig/foo/args/argsfoo-noeth -q -q tbotconfig.ci.tests.all
+          exitcode="$?"
+          if [[ "${exitcode}" != "0" ]];then
+            echo "doing all tests failed"
+            returncode=1
+          fi
           # and test second build host
           tbottest/newtbot_starter.py @tbotconfig/foo/args/argsfoo-noeth -q -q tbotconfig.ci.testbh.bhall
+          if [[ "${exitcode}" != "0" ]];then
+            echo "doing all build host tests failed"
+            returncode=1
+          fi
           tbottest/newtbot_starter.py @tbotconfig/foo/args/argsfoo-noeth -f buildername:sisyphus -q -q tbotconfig.ci.testbh.bhall
+          if [[ "${exitcode}" != "0" ]];then
+            echo "doing all sisyphus build host tests failed"
+            returncode=1
+          fi
+          exit "${returncode}"
